# Site configuration for StarfleetBio website
url: "https://starfleetbio.com" # the base hostname & protocol for your site, e.g. http://example.com
title: StarfleetBio
description: Computer-Aided Science For Modern R&D

# Site Theme settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dirt"
logo: /assets/images/logo_transparent_no_txt.png

# Site google analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-X8T7B9H77K"

# Site build settings
include:
  - _pages
  - assets
  - index.html
exclude:
  - TODO.md
  - README.md

plugins:
  - jekyll-feed
  - jekyll-include-cache

# default YAML front matter
defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
      show_date: true
      class: wide
      header:
        overlay_image: /assets/images/header.jpg
        caption: "Sunrise at [__CosmicCliffs-hero__](https://www.nasa.gov/image-article/nasas-webb-reveals-cosmic-cliffs-glittering-landscape-of-star-birth/)"
        og_image: /assets/images/logo.png
