# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: StarfleetBio
name: StarfleetBio
email: vanetten@starfleetbio.com
description: >- # this means to ignore newlines until "baseurl:"
  We help scientists accelerate biological discovery through computational tools, data analysis, and custom software.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://starfleetbio.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  vanetten
repository: starfleetbio/starfleetbio.com

# Build settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dirt"

include:
  - _pages
  - assets
  - index.html
exclude:
  - TODO.md
  - README.md

plugins:
  - jekyll-feed
  - jekyll-include-cache

# settings for author profile
author:
  name   : "William Van Etten"
  avatar : "/assets/images/headshot.jpg"
  bio    : "I enjoy writing about things I'm interested in - mostly science, computing, cloud, AI and software engineering."
  location: "Dover, NH"
  github : vanetten
  linkedin: william-van-etten-8b956b17
  email  : vanetten@starfleetbio.com

# google analytics
  google_analytics: "G-X8T7B9H77K"

# pagination for blog page
paginate: 10 # number of posts to show
paginate_path: /page:num/

# default YAML front matter
defaults:
  # all
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
      class: wide
      title: " "
      title_separator: "|"
  # posts
  - scope:
      path: ""
      type: posts
    values:
      toc: true
      toc_label: "Contents"
      read_time: false
      comments: true
  # portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      author_profile: false
      excerpt: ""
      sidebar:
        nav: "portfolio"

# collections
collections:
  portfolio:
    output: true
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
